project:
  type: website
  output-dir: docs

website:
  title: "Ethan Blacher"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resources.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    page-layout: full
    #toc: true

editor: visual

