project:
  type: website
  output-dir: docs

website:
  title: "Ethan Blacher"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - posts.qmd # add your posts.qmd file to your navbar!
      - text: Photos
        href: photogallery.qmd #add your photogallery.qmd to your navbar!

format:
  html:
    theme: 
      - slate
      - mystyles.scss
    mainfont: Crimson Text
    css: styles.css
    page-layout: full
    #toc: true

editor: visual

