project:
  type: website
  output-dir: docs

website:
  title: <meta name="google-site-verification" content="qNCmtSUSGFXjzxO9mwZiF20njs-lkgQXxcVR3j9HQpg" />
  navbar:
    left:
      - href: index.qmd
        text: Home
      - posts.qmd # add your posts.qmd file to your navbar!
      - text: Photos
        href: photogallery.qmd #add your photogallery.qmd to your navbar!
      - text: Nature
        href: animalflix.qmd
        

format:
  html:
    theme: 
      - slate #changed the theme to slate
     # - mystyles.scss
    mainfont: Crimson Text #changed font to crimson text
    css: styles.css
    page-layout: full
    #toc: true

editor: visual

