project:
  type: website
  output-dir: docs

website:
  title: "Ethan Blacher"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - posts.qmd # add your posts.qmd file to your navbar!
      - photogallery.qmd #add your photogallery.qmd to your navbar!

format:
  html:
    theme: slate
    css: styles.css
    mainfont: Crimson Text
    page-layout: full
    #toc: true

editor: visual

